version: '3.4'

services:
  app:
    build: .
    ports:
      - 8081:8080
    depends_on:
      - sql_server
    environment:
      ConnectionStrings__DefaultConnection: "Server=sql_server;Database=CallRecordDb;User=sa;Password=TechTest112358.#;"
      
  sql_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "TechTest112358.#"
    ports:
      - 1433:1433
    container_name: techtest_sql_server_1
    hostname: techtest_sql_server_1
    restart: unless-stopped
    volumes:
      - mssql-db-vol:/var/opt/mssql   # Mount a volume to persist SQL Server data
      
  unit-tests:
    container_name: techtest-unit-tests-unit-tests
    build:
      context: .
      dockerfile: Dockerfile
      target: unit-tests
    volumes:
      - ./test-reports:/reports   # Mount a volume to store test reports
      
  integration-tests:
    container_name: techtest-integration-tests
    build:
        context: .
        dockerfile: Dockerfile
        target: integration-tests
    
  create-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "TechTest112358.#"
    ports:
      - 1434:1433
    container_name: integration_db
    hostname: integration_db
    restart: unless-stopped
      # Mount a volume to persist SQL Server data

networks:
  default:
    external:
      name: techtest-network

volumes:
  mssql-db-vol: